version: 2

sources:
  - name: raw
    description: Raw data from e-commerce system
    schema: raw
    tables:
      - name: customers
        description: Customer information
        columns:
          - name: customer_id
            description: Primary key

      - name: products
        description: Product information
        columns:
          - name: product_id
            description: Primary key

      - name: orders
        description: Order header information
        columns:
          - name: order_id
            description: Primary key

      - name: order_items
        description: Order line items
        columns:
          - name: order_item_id
            description: Primary key

      - name: product_categories
        description: Product category information
        columns:
          - name: category_id
            description: Primary key

      - name: brands
        description: Brand information
        columns:
          - name: brand_id
            description: Primary key
